<?php

use ilhamrhmtkbr\App\Http\Controller\CandidateController;
use ilhamrhmtkbr\App\Http\Controller\EmployeeController;
use ilhamrhmtkbr\App\Http\Controller\HomeController;
use ilhamrhmtkbr\App\Http\Controller\HrController;
use ilhamrhmtkbr\App\Http\Controller\UserController;
use ilhamrhmtkbr\App\Facades\Router;
use ilhamrhmtkbr\App\Http\Middleware\AuthMiddleware;
use ilhamrhmtkbr\App\Http\Middleware\RoleMiddleware;
use ilhamrhmtkbr\App\Http\Middleware\UrlParameterMiddleware;

Router::add('GET', '/', HomeController::class, 'index');

Router::add('GET', '/user/register', UserController::class, 'viewRegister',[AuthMiddleware::class]);
Router::add('GET', '/user/login', UserController::class, 'viewLogin',[AuthMiddleware::class]);
Router::add('GET', '/user/dashboard', UserController::class, 'viewDashboard', [AuthMiddleware::class]);
Router::add('GET', '/user/advance/personal', UserController::class, 'viewPersonal', [AuthMiddleware::class]);
Router::add('GET', '/user/advance/skill', UserController::class, 'viewSkill', [AuthMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/user/advance/social', UserController::class, 'viewSocial', [AuthMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/user/profile/education', UserController::class, 'viewEducation', [AuthMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/user/profile/experience', UserController::class, 'viewExperience', [AuthMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/user/profile/portfolio', UserController::class, 'viewPortfolio', [AuthMiddleware::class, UrlParameterMiddleware::class]);
Router::add('POST', '/user/register', UserController::class, 'postRegister', [AuthMiddleware::class]);
Router::add('POST', '/user/login', UserController::class, 'postLogin', [AuthMiddleware::class]);
Router::add('GET', '/user/logout', UserController::class, 'doLogout', [AuthMiddleware::class]);
Router::add('POST', '/user/update-name', UserController::class, 'postUpdateName', [AuthMiddleware::class]);
Router::add('POST', '/user/update-email', UserController::class, 'postUpdateEmail', [AuthMiddleware::class]);
Router::add('POST', '/user/update-password', UserController::class, 'postUpdatePassword', [AuthMiddleware::class]);
Router::add('POST', '/user/advance/personal', UserController::class, 'postAdvancePersonal', [AuthMiddleware::class]);
Router::add('POST', '/user/advance/skill', UserController::class, 'postAdvanceSkill', [AuthMiddleware::class]);
Router::add('POST', '/user/advance/social', UserController::class, 'postAdvanceSocial', [AuthMiddleware::class]);
Router::add('POST', '/user/profile/education', UserController::class, 'postProfileEducation', [AuthMiddleware::class]);
Router::add('POST', '/user/profile/experience', UserController::class, 'postProfileExperience', [AuthMiddleware::class]);
Router::add('POST', '/user/profile/portfolio', UserController::class, 'postProfilePortfolio', [AuthMiddleware::class]);
Router::add('DELETE', '/user/advance/skill', UserController::class, 'deleteAdvanceSkill', [AuthMiddleware::class]);
Router::add('DELETE', '/user/advance/social', UserController::class, 'deleteAdvanceSocial', [AuthMiddleware::class]);
Router::add('DELETE', '/user/profile/experience', UserController::class, 'deleteProfileExperience', [AuthMiddleware::class]);
Router::add('DELETE', '/user/profile/education', UserController::class, 'deleteProfileEducation', [AuthMiddleware::class]);
Router::add('DELETE', '/user/profile/portfolio', UserController::class, 'deleteProfilePortfolio', [AuthMiddleware::class]);

Router::add('GET', '/candidate/jobs', CandidateController::class, 'viewJobs', [AuthMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/candidate/job', CandidateController::class, 'viewJob', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/candidate/job', CandidateController::class, 'postJob', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('GET', '/candidate/applied', CandidateController::class, 'viewApplied', [AuthMiddleware::class, RoleMiddleware::class]);

Router::add('GET', '/hr/candidates/download', HrController::class, 'downloadPdfCandidates', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/candidates', HrController::class, 'viewCandidates', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/candidate/details', HrController::class, 'viewCandidateDetails', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employees/download', HrController::class, 'downloadPdfEmployees', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employees', HrController::class, 'viewEmployees', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/details', HrController::class, 'viewEmployeeDetails', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/attendance/download', HrController::class, 'downloadPdfEmployeeAttendance', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('GET', '/hr/employee/attendance', HrController::class, 'viewEmployeeAttendance', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/attendance-rules/download', HrController::class, 'downloadPdfEmployeeAttendanceRules', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('GET', '/hr/employee/attendance-rules', HrController::class, 'viewEmployeeAttendanceRules', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/contracts/download', HrController::class, 'downloadPdfEmployeeContracts', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('GET', '/hr/employee/contracts', HrController::class, 'viewEmployeeContracts', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/leave-requests/download', HrController::class, 'downloadPdfEmployeeLeaveRequests', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('GET', '/hr/employee/leave-requests', HrController::class, 'viewEmployeeLeaveRequests', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/overtime/download', HrController::class, 'downloadPdfEmployeeOvertime', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/overtime', HrController::class, 'viewEmployeeOvertime', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/payrolls/download', HrController::class, 'downloadPdfEmployeePayrolls', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('GET', '/hr/employee/payrolls', HrController::class, 'viewEmployeePayrolls', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/project-assignments/download', HrController::class, 'downloadPdfEmployeeProjectAssignment', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/employee/project-assignments', HrController::class, 'viewEmployeeProjectAssignments', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company', HrController::class, 'viewCompany', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('GET', '/hr/company/employee/projects/download', HrController::class, 'downloadPdfCompanyEmployeeProjects', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company/employee/projects', HrController::class, 'viewCompanyEmployeeProjects', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company/employee/roles/download', HrController::class, 'downloadPdfCompanyEmployeeRoles', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company/employee/roles', HrController::class, 'viewCompanyEmployeeRoles', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company/office/departments/download', HrController::class, 'downloadPdfCompanyOfficeDepartments', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company/office/departments', HrController::class, 'viewCompanyOfficeDepartments', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company/office/financial-transactions/download', HrController::class, 'downloadPdfCompanyOfficeFinancialTransactions', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company/office/financial-transactions', HrController::class, 'viewCompanyOfficeFinancialTransactions', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company/office/recruitments/download', HrController::class, 'downloadPdfCompanyOfficeRecruitments', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/hr/company/office/recruitments', HrController::class, 'viewCompanyOfficeRecruitments', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('POST', '/hr/candidate/interview', HrController::class, 'postCandidateInterview', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/candidate/update', HrController::class, 'updateCandidateStatus', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/employee', HrController::class, 'postEmployee', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/employee/attendance-rule', HrController::class, 'createOrUpdateEmployeeAttendanceRule', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/employee/contract', HrController::class, 'createOrUpdateEmployeeContract', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/employee/leave-request', HrController::class, 'createOrUpdateEmployeeLeaveRequest', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/employee/overtime', HrController::class, 'createOrUpdateEmployeeOvertime', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/employee/payroll', HrController::class, 'createOrUpdateEmployeePayroll', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/employee/project-assignment', HrController::class, 'createOrUpdateEmployeeProjectAssignment', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/company/employee/project', HrController::class, 'createOrUpdateCompanyEmployeeProject', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/company/employee/role', HrController::class, 'createOrUpdateCompanyEmployeeRole', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/company/office/department', HrController::class, 'createOrUpdateCompanyOfficeDepartment', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/company/office/financial-transaction', HrController::class, 'createOrUpdateCompanyOfficeFinancialTransaction', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('POST', '/hr/company/office/recruitment', HrController::class, 'createOrUpdateCompanyOfficeRecruitment', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/employee', HrController::class, 'deleteEmployee', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/employee/attendance-rule', HrController::class, 'deleteEmployeeAttendanceRule', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/employee/contract', HrController::class, 'deleteEmployeeContract', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/employee/leave-request', HrController::class, 'deleteEmployeeLeaveRequest', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/employee/overtime', HrController::class, 'deleteEmployeeOvertime', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/employee/payroll', HrController::class, 'deleteEmployeePayroll', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/employee/project-assignment', HrController::class, 'deleteEmployeeProjectAssignment', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/company/employee/project', HrController::class, 'deleteCompanyEmployeeProject', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/company/employee/role', HrController::class, 'deleteCompanyEmployeeRole', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/company/office/department', HrController::class, 'deleteCompanyOfficeDepartment', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/company/office/financial-transaction', HrController::class, 'deleteCompanyOfficeFinancialTransaction', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('DELETE', '/hr/company/office/recruitment', HrController::class, 'deleteCompanyOfficeRecruitment', [AuthMiddleware::class, RoleMiddleware::class]);

Router::add('GET', '/employee', EmployeeController::class, 'viewEmployee', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('GET', '/employee/attendance/check', EmployeeController::class, 'attendanceCheck', [AuthMiddleware::class, RoleMiddleware::class]);
Router::add('GET', '/employee/attendance/download', EmployeeController::class, 'DownloadPdfAttendance', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/attendance', EmployeeController::class, 'viewAttendance', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/contracts/download', EmployeeController::class, 'DownloadPdfContracts', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/contracts', EmployeeController::class, 'viewContracts', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/leave-requests/download', EmployeeController::class, 'DownloadPdfLeaveRequests', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/leave-requests', EmployeeController::class, 'viewLeaveRequests', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/overtime/download', EmployeeController::class, 'DownloadPdfOvertime', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/overtime', EmployeeController::class, 'viewOvertime', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/payrolls/download', EmployeeController::class, 'DownloadPdfPayrolls', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/payrolls', EmployeeController::class, 'viewPayrolls', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/project-assignments/download', EmployeeController::class, 'DownloadPdfProjectAssignments', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);
Router::add('GET', '/employee/project-assignments', EmployeeController::class, 'viewProjectAssignments', [AuthMiddleware::class, RoleMiddleware::class, UrlParameterMiddleware::class]);